// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWGGw5q63BomaWsiKtl5oVQVOFvM9I_M',
    appId: '1:1039406573210:web:20662fdc192f26fd126123',
    messagingSenderId: '1039406573210',
    projectId: 'tva-recipefy',
    authDomain: 'tva-recipefy.firebaseapp.com',
    storageBucket: 'tva-recipefy.appspot.com',
    measurementId: 'G-L10LL2BDX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDP80tKovfNQY7VWSNNIo_8-lGGMEurPo',
    appId: '1:1039406573210:android:e1ab09cd135a3909126123',
    messagingSenderId: '1039406573210',
    projectId: 'tva-recipefy',
    storageBucket: 'tva-recipefy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2JmcxQLDURd1YK1REuqYBEXY3SsQgS8I',
    appId: '1:1039406573210:ios:aa55fdeb63ed59f7126123',
    messagingSenderId: '1039406573210',
    projectId: 'tva-recipefy',
    storageBucket: 'tva-recipefy.appspot.com',
    iosBundleId: 'com.example.recipefy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2JmcxQLDURd1YK1REuqYBEXY3SsQgS8I',
    appId: '1:1039406573210:ios:aa55fdeb63ed59f7126123',
    messagingSenderId: '1039406573210',
    projectId: 'tva-recipefy',
    storageBucket: 'tva-recipefy.appspot.com',
    iosBundleId: 'com.example.recipefy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWGGw5q63BomaWsiKtl5oVQVOFvM9I_M',
    appId: '1:1039406573210:web:9dbd30548229f9dd126123',
    messagingSenderId: '1039406573210',
    projectId: 'tva-recipefy',
    authDomain: 'tva-recipefy.firebaseapp.com',
    storageBucket: 'tva-recipefy.appspot.com',
    measurementId: 'G-VEQ3GEH0JR',
  );
}
